import { useState } from 'react';
import 'bootstrap/dist/css/bootstrap.css';

function Quotes({ quotes }) {
    const [loading, setLoading] = useState(false)

    return (
        <article className="col-12 table-responsive">
            <table className="table caption-top table-bordered text-readable text-large">
                <caption>
                    Some quotes generated by SSR 😉
                </caption>
                <thead>
                    <tr className="table-primary">
                        <th scope="col">Category</th>
                        <th scope="col">Quotes</th>
                    </tr>
                </thead>
                <tbody id="tableSummary">
                    {quotes.map((quote) => (
                        <tr key={quote.category}>
                            <th scope='row'>
                                {quote.category}
                            </th>
                            <td>
                                <ol>
                                    {quote.quoteList.map(quoteItem => (
                                        <li className='mt-2' key={quoteItem.quoteText}>
                                            {quoteItem.quoteText}
                                            - <span className='text-success'>{quoteItem.author}</span>
                                        </li>
                                    ))}
                                </ol>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </article>
    )
}

export async function getServerSideProps() {
    const res = await fetch(`${process.env.API_URL}/api/quotes`)
    const quotes = await res.json()
    return { props: { quotes } }
}

export default Quotes;
